### ISSUE TITLE
Always getting Product Not Found

### ISSUE THREAD

**Issue by takielias** [DevShoesed/amazon-scrape#1]
![image](https://user-images.githubusercontent.com/38932580/145338898-88ce0842-4327-42b0-8664-a779345655e8.png)

Every time I got this. Any solution?

**Comment by DevShoesed** [comment]
Hi, you are using a description, you must use ASIN that is an Identification Numberr

https://en.wikipedia.org/wiki/Amazon_Standard_Identification_Number
